name: Build and Release

permissions:
  contents: write
  actions: read
  checks: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

on:
  push:
    branches:
      - 'feat/add-login-page*'
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: 'add-login-page-15886046244164752361'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.27.0'
        channel: 'stable'
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Setup signing
      run: |
        # 创建签名密钥文件
        echo "${{ secrets.SIGNING_KEY }}" | base64 -d > android/wordflow-key.jks
        
        # 创建key.properties文件
        echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" > android/key.properties
        echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
        echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
        echo "storeFile=../wordflow-key.jks" >> android/key.properties
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: build/app/outputs/flutter-apk/app-release.apk
